# Generated by Django 6.0.7 on 2026-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=70, unique=True)),
                ('badge_style', models.CharField(default='badge-cyan', help_text='Color class, e.g. badge-cyan, badge-blue, badge-emerald, badge-purple, badge-amber', max_length=50)),
            ],
            options={
                'verbose_name': 'Project Technology Tag',
                'verbose_name_plural': 'Project Technology Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.CharField(help_text='Concise 1-2 sentence summary for project cards', max_length=300)),
                ('problem_statement', models.TextField(help_text='The real-world problem or operational bottleneck this project was engineered to solve')),
                ('solution_statement', models.TextField(help_text='Detailed engineering solution, user journey, and technical resolution')),
                ('architecture_description', models.TextField(help_text='Technical architecture, data modeling, backend services, API contracts, and integration points')),
                ('key_features', models.TextField(help_text='Breakdown of key capabilities, operational workflows, and security implementations')),
                ('challenges_and_learnings', models.TextField(help_text='Performance bottlenecks overcome, trade-offs made, and architectural insights gained')),
                ('image', models.ImageField(blank=True, help_text='Primary project mockup or architecture diagram', null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, help_text='Link to public GitHub repository (leave empty if proprietary or in-progress)')),
                ('live_url', models.URLField(blank=True, help_text='Link to live deployment or interactive demonstration')),
                ('featured', models.BooleanField(db_index=True, default=False, help_text='Pin to the Featured Projects showcase on the homepage')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Uncheck to hide project from public view')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('date_created', models.DateField(auto_now_add=True, help_text='Date when project record was created')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='projects.projecttechnology')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['display_order', '-date_created'],
            },
        ),
    ]
