# Generated by Django 6.0.7 on 2026-09-25 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_type', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education'), ('certification', 'Certification'), ('milestone', 'Milestone & Project Journey')], default='work', max_length=30)),
                ('title', models.CharField(help_text='Job title, degree, or certificate name', max_length=180)),
                ('organization', models.CharField(help_text='Company, University, or Issuing Authority', max_length=180)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('start_date', models.CharField(help_text='e.g. 2023 or Jan 2023', max_length=60)),
                ('end_date', models.CharField(blank=True, help_text='e.g. Present or Dec 2024 (leave blank if current)', max_length=60)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Key responsibilities, architectural accomplishments, technologies used, or course summary')),
                ('credential_url', models.URLField(blank=True, help_text='Optional link to credential, company, or course verification')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experience / Journey Entry',
                'verbose_name_plural': 'Experience & Journey Entries',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Joseph Ashirumah', max_length=150)),
                ('professional_title', models.CharField(default='Full-Stack Software Engineer', max_length=200)),
                ('eyebrow_text', models.CharField(default='FULL-STACK SOFTWARE ENGINEER', help_text='Small eyebrow tag above the main hero headline', max_length=150)),
                ('headline', models.CharField(default='Building reliable software for the web.', max_length=255)),
                ('subheadline', models.TextField(default="I'm a Full-Stack Software Engineer specializing in Python, Django, SQL and modern frontend technologies. I build practical, scalable and user-focused web applications from database to interface.")),
                ('short_bio', models.TextField(default='Full-stack engineer passionate about software craft, architectural clarity, and building dependable web applications with Python, Django, and SQL.')),
                ('about_text', models.TextField(default='I’m a Full-Stack Software Engineer focused on building practical, maintainable and scalable web applications. My core specialization is Python and Django on the backend, SQL and relational databases for data management, and modern frontend technologies for building responsive user experiences.\n\nI approach software engineering with a product-oriented mindset—prioritizing robust data schemas, clean API interfaces, intuitive UX, and clean code that teams can confidently maintain and extend. Whether architecting backend business logic or polishing frontend interactions, I build solutions engineered for performance, security, and long-term reliability.')),
                ('profile_photo', models.ImageField(blank=True, help_text='Professional headshot or profile photo', null=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, help_text='Upload your resume / CV document (PDF recommended)', null=True, upload_to='cv/')),
                ('email', models.EmailField(default='joseph.ashirumah@example.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='+1 (555) 000-0000 [EDIT THIS]', max_length=60)),
                ('location', models.CharField(default='Available for Remote & Relocation [EDIT THIS]', max_length=150)),
                ('status_badge', models.CharField(default='Open to Software Engineering Opportunities', help_text='Visible badge indicating your current availability', max_length=120)),
                ('status_active', models.BooleanField(default=True, help_text='Toggle visibility of the availability status indicator')),
                ('github_url', models.URLField(blank=True, default='https://github.com/josephashirumah [EDIT THIS]')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/in/josephashirumah [EDIT THIS]')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('hero_code_snippet', models.TextField(blank=True, default='# Developer Profile\nengineer = {\n    "name": "Joseph Ashirumah",\n    "role": "Full-Stack Software Engineer",\n    "core_stack": ["Python", "Django", "SQL", "JavaScript", "React"],\n    "focus": "Scalable web applications & robust APIs",\n    "status": "Ready to build high-impact software",\n    "hireable": True\n}\n\ndef ship_value():\n    return engineer["core_stack"] + ["Reliability", "Clean Architecture"]', help_text='Python code preview rendered in the interactive hero terminal card')),
            ],
            options={
                'verbose_name': 'Profile & Bio',
                'verbose_name_plural': 'Profile & Bio',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Joseph Ashirumah | Full-Stack Software Engineer', max_length=150)),
                ('meta_description', models.TextField(default='Portfolio of Joseph Ashirumah, Full-Stack Software Engineer specializing in Python, Django, SQL, and robust modern web architectures.')),
                ('footer_text', models.CharField(default='Crafting scalable web applications with clean architecture and modern engineering standards.', max_length=255)),
                ('contact_email', models.EmailField(default='joseph.ashirumah@example.com', max_length=254)),
                ('enable_contact_form', models.BooleanField(default=True)),
                ('enable_hire_cta', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('backend', 'Backend Engineering'), ('frontend', 'Frontend Development'), ('database', 'Database & Data Systems'), ('tools', 'Tools & DevOps')], max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='bi-cpu', help_text='Bootstrap icon class (e.g. bi-server, bi-code-slash, bi-database, bi-gear)', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('email', 'Email (mailto)'), ('website', 'Portfolio / Blog')], max_length=30)),
                ('label', models.CharField(blank=True, help_text="Display label, e.g. 'GitHub'", max_length=60)),
                ('url', models.CharField(help_text='Destination URL or mailto: link', max_length=255)),
                ('icon_class', models.CharField(default='bi-link-45deg', help_text='Bootstrap icon (e.g. bi-github, bi-linkedin, bi-twitter-x, bi-envelope)', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='ValuePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('icon', models.CharField(default='bi-check-circle', help_text='Bootstrap icon class (e.g. bi-layers, bi-server, bi-database-check, bi-lightbulb, bi-graph-up-arrow)', max_length=80)),
                ('short_summary', models.TextField(help_text='Concise description of the engineering value provided')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Why Work With Me Card',
                'verbose_name_plural': 'Why Work With Me Cards',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, help_text='Bootstrap or Devicon class, e.g. bi-filetype-py, bi-database, bi-git', max_length=80)),
                ('is_primary_stack', models.BooleanField(default=False, help_text='Mark as part of the core highlighted stack (e.g. Python, Django, SQL)')),
                ('short_description', models.CharField(blank=True, help_text="Short highlight, e.g. 'ORM modeling, authentication & scalable services'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill / Technology',
                'verbose_name_plural': 'Skills & Technologies',
                'ordering': ['order', 'name'],
            },
        ),
    ]
