# Generated by Django 5.0.6 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_url",
            field=models.URLField(blank=True, default="https://github.com/ashirumah11"),
        ),
    ]
