# Generated by Django 5.0.6 on 2026-09-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_profile_github_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="platform",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("linkedin", "LinkedIn"),
                    ("x", "X (Twitter)"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email (mailto)"),
                    ("website", "Portfolio / Blog"),
                ],
                max_length=30,
            ),
        ),
    ]
